---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chriwymq/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp education.html $DEPLOYPATH
    - /bin/cp experience.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH